apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      run: nginx-dep
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-dep
    spec:
      containers:
      - name: nginx-container
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          containerPort: 22
          containerPort: 443
          
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    run: nginx-dep
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      port: 443
      targetPort: 433
      port: 22
      targetPort: 22
