apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps-dep
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps-dep
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30001
        - containerPort: 30002
        livenessProbe:
          exec:
            command:
            - bash
            - /health.sh
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: alae
  name: ftps-service
spec:
  selector:
    app: ftps-dep
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
      name: connectionport
    - port: 30001
      targetPort: 30001
      name: datatransport
    - port: 30002
      targetPort: 30002
      name: datatransport2