apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      run: mysql-dep
  replicas: 1
  template:
    metadata:
      labels:
        run: mysql-dep
    spec:
      containers:
      - name: mysql-container
        image: mysql-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    run: mysql-dep
  ports:
    - port: 8080
      targetPort: 3306