apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      run: nginx-dep
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-dep
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        livenessProbe:
          exec:
            command:
            - bash
            - /health.sh
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: alae
  name: nginx-service
spec:
  selector:
    run: nginx-dep
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: httpport
    - port: 443
      targetPort: 443
      name: httpsport
    - port: 22
      targetPort: 22
      name: sshport