apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      run: phpmyadmin-dep
  replicas: 1
  template:
    metadata:
      labels:
        run: phpmyadmin-dep
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    run: phpmyadmin-dep
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30003