apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      run: wordpress-dep
  replicas: 1
  template:
    metadata:
      labels:
        run: wordpress-dep
    spec:
      containers:
      - name: wordpress-container
        image: wordpress-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: alae
  name: wordpress-service
spec:
  selector:
    run: wordpress-dep
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 5050
      # nodePort: 30000